Address 44
PhilipFlyvholm/learnit-plus-plus pull request #46
Opened 2023-11-15 14:38 UTC by lucasfth

My fix was to just remove the stars.
The reasoning is that they can not be used to unstar the starred courses anyway.

<img width="1680" alt="image" src="https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/94063597/7a88f202-1dae-40f7-bcf5-5b99c78de557">

2023-11-16 20:48 UTC, PatrickMatthiesen requested changes
It might just be a better idea to remove or unset the position from the selector in main.css?
https://github.com/PhilipFlyvholm/learnit-plus-plus/blob/1bdfe5e35da62799c65c7c2421d79489646075a3/src/styles/main.css#L158-L162
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/c5e0fb6f-8ec7-401f-a95e-d8dca9290f66)

2023-11-16 20:48 UTC, PatrickMatthiesen commented on src/styles/main.css
> +.text-primary {
Its probably not a good idea to hide this selector as it is a default color selector.
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/461cf433-a4da-46a6-b15f-8b9715741e15)
As you can see then it has hidden a button somewhere

2023-11-18 10:14 UTC, lucasfth commented
I tried to unset the position, which resulted in a fairly inconsistent look:

<img width="1149" alt="image" src="https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/94063597/d5dfd757-afe1-4962-bb7f-073b3da2e995">

I tried to move the star icon to the bottom right. But due to the reorganization of the texts I seem to be unable to make the bottom fill out more (view below):

<img width="359" alt="image" src="https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/94063597/f593472e-5553-4bd3-af61-535f511ebc97">

If it could be done it should be possible to make the star icon fit to the bottom right of the parent

2023-11-18 11:12 UTC, PatrickMatthiesen commented
Maybe it would just be an easier fix to set the width of the link/name of the course to 90-95%. That way we force the header to wrap before it gets to the star?
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/214d935c-e2f4-4594-85bc-09b03697f67c)
![image](https://github.com/PhilipFlyvholm/learnit-plus-plus/assets/43612965/1cc7c974-624a-438d-bf46-1bd68ee22108)

2023-11-20 13:48 UTC, PhilipFlyvholm commented
If we instead just removed some CSS I added some time ago then it would be at the bottom and respect the titles:

See: https://github.com/PhilipFlyvholm/learnit-plus-plus/blob/1bdfe5e35da62799c65c7c2421d79489646075a3/src/styles/main.css#L158C2-L162C2

The position at the top was to try to match the old LearnIT, and because the original feature request wanted the order reversed like it is currently. Of course, the star part could have been implemented better.

2023-12-05 09:51 UTC, PhilipFlyvholm commented
@lucasfth I have pushed a change that solves the same problem but with a different solution. I hope this is okay.

2023-12-05 11:02 UTC, PatrickMatthiesen approved these changes
Looks good to me :octocat:

2023-12-05 11:04 UTC, merged